import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter/foundation.dart';
import '../../data/local/hive_service.dart';
import '../../presentation/providers/auth_provider.dart';

final cloudSyncServiceProvider = Provider<CloudSyncService>((ref) {
  return CloudSyncService(ref);
});

class CloudSyncService {
  final Ref _ref;
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  CloudSyncService(this._ref);

  /// Backs up all relevant Hive data to Firestore
  Future<void> backupData() async {
    final userId = _ref.read(currentUserIdProvider);
    if (userId == null) return;

    try {
      final subjectsBox = Hive.box<Map>(HiveService.subjectsBox);
      final slotsBox = Hive.box<Map>(HiveService.timetableSlotsBox);
      final recordsBox = Hive.box<Map>(HiveService.attendanceRecordsBox);
      final metaBox = Hive.box<Map>(HiveService.metaBox);

      final backupData = {
        'subjects': _boxToMap(subjectsBox),
        'slots': _boxToMap(slotsBox),
        'records': _boxToMap(recordsBox),
        'meta': _boxToMap(metaBox),
        'updatedAt': FieldValue.serverTimestamp(),
      };

      await _firestore.collection('users').doc(userId).collection('backup').doc('hive_data').set(backupData);
      debugPrint('Cloud sync backup completed successfully.');
    } catch (e) {
      debugPrint('Cloud sync backup failed: $e');
    }
  }

  /// Restores data from Firestore to local Hive
  Future<void> restoreData() async {
    final userId = _ref.read(currentUserIdProvider);
    if (userId == null) return;

    try {
      final doc = await _firestore.collection('users').doc(userId).collection('backup').doc('hive_data').get();
      if (!doc.exists) return; // No backup found

      final data = doc.data();
      if (data == null) return;

      final subjectsBox = Hive.box<Map>(HiveService.subjectsBox);
      final slotsBox = Hive.box<Map>(HiveService.timetableSlotsBox);
      final recordsBox = Hive.box<Map>(HiveService.attendanceRecordsBox);
      final metaBox = Hive.box<Map>(HiveService.metaBox);

      // Clear existing data
      await subjectsBox.clear();
      await slotsBox.clear();
      await recordsBox.clear();
      await metaBox.clear();

      // Restore data
      if (data['subjects'] != null) {
        await _restoreBox(subjectsBox, Map<String, dynamic>.from(data['subjects']));
      }
      if (data['slots'] != null) {
        await _restoreBox(slotsBox, Map<String, dynamic>.from(data['slots']));
      }
      if (data['records'] != null) {
        await _restoreBox(recordsBox, Map<String, dynamic>.from(data['records']));
      }
      if (data['meta'] != null) {
        await _restoreBox(metaBox, Map<String, dynamic>.from(data['meta']));
      }

      debugPrint('Cloud sync restore completed successfully.');
    } catch (e) {
      debugPrint('Cloud sync restore failed: $e');
    }
  }

  Map<String, dynamic> _boxToMap(Box<Map> box) {
    final map = <String, dynamic>{};
    for (final key in box.keys) {
      final val = box.get(key);
      if (val != null) {
        // Ensure keys are strings for Firestore
        final stringMap = <String, dynamic>{};
        val.forEach((k, v) {
          if (v is DateTime) {
            stringMap[k.toString()] = v.toIso8601String();
          } else {
            stringMap[k.toString()] = v;
          }
        });
        map[key.toString()] = stringMap;
      }
    }
    return map;
  }

  Future<void> _restoreBox(Box<Map> box, Map<String, dynamic> data) async {
    for (final entry in data.entries) {
      final mapVal = Map<dynamic, dynamic>.from(entry.value);
      // Restore DateTimes if they look like iso strings
      final parsedMap = <dynamic, dynamic>{};
      mapVal.forEach((k, v) {
        if (v is String && _isIso8601(v)) {
          parsedMap[k] = DateTime.parse(v);
        } else {
          parsedMap[k] = v;
        }
      });
      await box.put(entry.key, parsedMap);
    }
  }

  bool _isIso8601(String str) {
    // Simple heuristic for ISO string generated by DateTime.toIso8601String()
    return str.length >= 20 && str.contains('T') && (str.endsWith('Z') || str.contains('.'));
  }
}
